- name: Upgrade System
  apt: upgrade=dist update_cache=yes

- name: Add php repository
  apt_repository:
   repo: 'ppa:ondrej/php'

- name: Install PHP
  apt: name=php7.4 state=latest

- name: Install PHP MB
  apt: name=php7.4-mbstring state=latest

- name: Install PHP cli
  apt: name=php7.4-cli state=latest

- name: Install PHP json
  apt: name=php7.4-json state=latest 

- name: Install PHP common
  apt: name=php7.4-common state=latest 

- name: Install PHP mysql
  apt: name=php7.4-mysql state=latest 

- name: Install PHP zip
  apt: name=php7.4-zip state=latest 

- name: Install PHP gd
  apt: name=php7.4-gd state=latest 

- name: Install PHP curl
  apt: name=php7.4-curl state=latest 

- name: Install PHP XML
  apt: name=php7.4-xml state=latest

- name: Install PHP bcmath
  apt: name=php7.4-bcmath state=latest 

- name: Install unzip
  apt: name=unzip state=latest


- name: Download php-composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer

- name: install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: make composer executable
  file: 
    path: /usr/local/bin/composer
    mode: a+x
    state: file

- name: install apache2 server
  apt:
     name: apache2
     state: present

- name: remove old project
  shell: sudo rm -fR /opt/{{ vhost_name }}

- name: checkout latest code from github
  git: >
    repo=http://192.168.95.249/root/build-back.git
    dest=/opt/{{ vhost_name }}
    force=yes
    accept_hostkey=yes

- name: remove old project
  shell: sudo rm -fR /var/www/html/{{ vhost_name }}/

- name: copy lavarel project
  shell: sudo mv /opt/{{ vhost_name }} /var/www/html/

- name: Change permission
  shell: sudo chgrp -R www-data /var/www/html/{{ vhost_name }}/

- name: Change permission
  shell: sudo chmod -R 775 /var/www/html/{{ vhost_name }}/storage

- name: Remove default apache vhost config from sites-enabled
  file: name=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Create apache vhosts for  domain
  template: src=web.conf.j2 dest="/etc/apache2/sites-available/{{ vhost_name }}.conf" owner=www-data group=www-data mode=0644

- name: Update a2ensite
  command: a2ensite {{ vhost_name }}

- name: Enable the Apache rewrite module
  command:  a2enmod rewrite

  notify:
    - restart apache2
